package ntut.csie.taskService.useCase.burndownChart.get;

import ntut.csie.taskService.useCase.UseCase;

public interface GetBurndownChartPointsBySprintDatesAndTaskIdsUseCase extends UseCase<GetBurndownChartPointsBySprintDatesAndTaskIdsInput, GetBurndownChartPointsBySprintDatesAndTaskIdsOutput>{

}
